language: go
go:
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - 1.12.x
    - tip

install:
  - go get golang.org/x/lint/golint
  - go get -t ./...

script:
  - golint $(go list ./... | grep -v /vendor/)
  - go test $(go list ./...| grep -v /vendor/)

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
